sprint1 completed
ClevertecFrontendLab/sprint1-RodionMas pull request #1
Opened 2023-01-25 16:03 UTC by RodionMas

2023-01-25 16:40 UTC, Gaurrus requested changes

2023-01-25 16:40 UTC, Gaurrus commented on public/index.html
> +  <head>
![image](https://user-images.githubusercontent.com/85307211/214620803-e98da18d-6d9f-4d2d-af24-10feb4434634.png)
вот тут текст за экран уплыл)

2023-01-25 16:40 UTC, Gaurrus commented on public/index.html
>      <meta charset="utf-8" />
![image](https://user-images.githubusercontent.com/85307211/214622031-3326e339-4000-40aa-a4f6-5a66513a46de.png)
обе кнопки должны отображаться одинаково

2023-01-25 16:55 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674665716/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674665716/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674665716/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674665716/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674665716/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674665716/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674665716/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674665716/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674665716/content-window.png)

2023-01-25 17:01 UTC, Gaurrus requested changes

2023-01-25 17:01 UTC, Gaurrus commented on public/index.html
> +  <head>
![image](https://user-images.githubusercontent.com/85307211/214629627-3e631281-766f-4dea-9822-8c1a431b5c90.png)
не исправлено, вот в дизайне вообще подругому)

2023-01-26 13:33 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674740036/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674740036/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674740036/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674740036/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674740036/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674740036/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674740036/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674740036/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/RodionMas/1674740036/content-window.png)

2023-01-26 13:49 UTC, Gaurrus approved these changes

2023-01-26 13:49 UTC, Gaurrus commented on src/pages/book/about-book/about-book.jsx
> +  console.log();
консолька зачем?)

2023-01-26 13:49 UTC, Gaurrus commented on src/pages/book/book-page.module.css
> +
пустой файл?)

2023-01-26 13:49 UTC, Gaurrus commented on src/pages/book/breadcrumbs/breadcrumbs.jsx
> +  console.log();
консолька

2023-01-26 13:49 UTC, Gaurrus commented on src/pages/book/detailed/detailed.jsx
> +  console.log();
консолька

2023-01-26 13:49 UTC, Gaurrus commented on src/pages/book/raiting/raiting.jsx
> +  console.log();
консолька

2023-01-26 13:49 UTC, Gaurrus commented on src/pages/book/raiting/raiting.jsx
> +        <img className={style.star} src={star} alt='raiting' />
не есть хорошо, для первого спринта пойдет, но в будущем придется переделывать каждую звезду отдельно для возможности задавать рейтинг и т.д.

2023-01-26 13:49 UTC, Gaurrus commented on src/pages/book/reviews/reviews.jsx
> +  console.log();
консолька

2023-01-26 13:49 UTC, Gaurrus commented on src/pages/main/footer/footer.jsx
> +          </svg>
страшненько, svg можно вставлять в img

2023-01-27 14:09 UTC, merged